A common function die() is introduced -- it terminates the program after displaying on stderr a message gives as argument.  The same message is used as program exit status.
All scripts are updated to use the new function and some of the
messages / exit statuses got changed too.

Streamline fatal error handling in rc scripts.

diff --git a/clone b/clone
--- a/clone
+++ b/clone
@@ -14,11 +14,9 @@ if(~ $#remote 0)
 if(~ $#local 0)
 	local=`{basename $remote .git}
 
-if(test -e $local){
-	echo $local already exists >[1=2]
-	exit exists
-}
-	
+if(test -e $local)
+	die 'repository already exists:' $local
+
 fn clone{
 	mkdir -p $local/.git
 	mkdir -p $local/.git/objects/pack/
@@ -57,20 +55,15 @@ fn clone{
 				print headhash > ".git/HEAD"
 			}
 		}
-	'} |[3] tr '\x0d' '\x0a'
-	x=$status
-	if(! ~ $x '|')
-		exit $0:^' '^$"x
+	'} |[3] tr '\x0d' '\x0a' || die $status
 
 	tree=/mnt/git/branch/heads/master/tree
 	echo checking out repository...
 	if(test -f .git/refs/remotes/origin/master){
 		cp .git/refs/remotes/origin/master .git/refs/heads/master
 		git/fs
-		@ {builtin cd $tree && tar cif /fd/1 .} | @ {tar xf /fd/0}
-		x=$status
-		if(! ~ $x '')
-			exit 'checkout: '^$"x
+		@ {builtin cd $tree && tar cif /fd/1 .} | @ {tar xf /fd/0} \
+			|| die 'checkout failed:' $status
 		for(f in `$nl{walk -f $tree | sed 's@^'$tree'/*@@'}){
 			if(! ~ $#f 0){
 				idx=.git/index9/tracked/$f
diff --git a/commit b/commit
--- a/commit
+++ b/commit
@@ -1,4 +1,4 @@
-#!/bin/rc
+#!/bin/rc -e
 rfork ne
 . /bin/git/common.rc
 
@@ -36,11 +36,8 @@ fn findbranch{
 		refpath=.git/refs/$branch
 		initial=true
 	}
-	if not{
-		echo invalid branch $branch >[1=2]
-		exit badbranch
-	}
-
+	if not
+		die 'invalid branch:' $branch
 }
 
 fn editmsg{
@@ -50,7 +47,7 @@ fn editmsg{
 	echo '#' $nl'# ' ^ `$nl{git/walk -fAMR} >> $msgfile.tmp
 	sam $msgfile.tmp
 	if(~ `{grep -v '^[ 	]*($|#.*$)' $msgfile.tmp | wc -l} 0)
-		exit 'empty commit message'
+		die 'empty commit message'
 	grep -v '^[ 	]*#' < $msgfile.tmp > $msgfile
 }
 
@@ -67,10 +64,7 @@ fn commit{
 	msg=`"{cat $msgfile}
 	if(! ~ $#parents 0)
 		pflags='-p'^$parents
-	hash=`{git/save -n $"name -e $"email  -m $"msg $pflags}
-	st=$status
-	if(~ $hash '')
-		exit nocommit
+	hash=`{git/save -n $"name -e $"email  -m $"msg $pflags || die $status}
 }
 
 fn update{
@@ -96,10 +90,8 @@ gitup
 
 msgfile=/tmp/git-msg.$pid
 mkdir -p .git/refs
-if(git/walk -q){
-	echo no changes to commit >[1=2]
-	exit clean
-}
+if(git/walk -q)
+	die 'nothing to commit'
 @{
 	flag e +
 	whoami
@@ -109,9 +101,4 @@ if(git/walk -q){
 	commit
 	update
 	cleanup
-}
-x=$status
-if(! ~ $x ''){
-	echo 'could not commit:' $x >[1=2]
-	exit $x
-}
+} || die 'could not commit:' $status
diff --git a/import b/import
--- a/import
+++ b/import
@@ -6,14 +6,7 @@ usage='
 	git/import [file ...]
 '
 
-fn die{
-	echo $patchname: $1 $2
-	exit $2
-}
-
 fn apply @{
-	flag +e
-
 	git/fs
 	email=''
 	name=''
@@ -26,7 +19,7 @@ fn apply @{
 	if not if(test -e /mnt/git/object/$branch/tree)
 		refpath=.git/HEAD
 	if not
-		exit 'invalid branch '$branch
+		die 'invalid branch:' $branch
 	awk '
 	BEGIN{
 		state="headers"
@@ -63,25 +56,17 @@ fn apply @{
 	END{
 		if(state != "diff")
 			exit("malformed patch: " state);
-		if(name == "" || email == "" || msg == "" || date == ""){
-			print "missing headers" > "/fd/2";
-			exit("missingheader");
-		}
+		if(name == "" || email == "" || msg == "" || date == "")
+			exit("missing headers");
 		printf "%s", name > "/env/name"
 		printf "%s", email > "/env/email"
 		printf "%s", msg > "/env/msg"
 		printf "%s", date > "/env/date"
 	}
-	'
-	st=$status
-	if(! ~ $st ''){
-		echo could not import: $st >[1=2]
-		exit badpatch
-	}
+	' || die 'could not import:' $status
 
 	# force re-reading env
 	rc -c '
-		flag -e
 		echo applying $msg | sed 1q
 		date=`{seconds $date}
 		files=`$nl{ape/patch -p1 < $diffpath | sed ''s/^patching file `(.*)''''/\1/''}
@@ -97,19 +82,10 @@ fn apply @{
 	'
 }
 
-fn import{
-	apply
-	st=$status
-	if(! ~ $st ''){
-		echo stdin: $st
-		exit $st
-	}
-}
-
 gitup
 
 patches=(/fd/0)
 if(! ~ $#* 0)
 	patches=$*
 for(f in $patches)
-	import < $f
+	apply < $f || die $status 
